### ISSUE TITLE
Validator - check for required properties in tileset.json

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles-validator#126]
@rms13

`validateTileset` is doing a much better job now, but there are still a lot of loose ends. In the code verify that all required properties are present and are the correct type. This will be a sweeping PR to bring `validateTileset` to completion and will require looking the spec and tileset.json schema closely.

**Comment by javagl** [comment]
This should have been closed via https://github.com/CesiumGS/3d-tiles-validator/pull/222#issuecomment-1265905466 

Having missing properties (like the missing `geometricError`) in a tileset like this
```
{
  "asset" : {
    "version" : "1.1"
  },
  "root" : {
    "boundingVolume" : {
      "box" : [ 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.5 ]
    },
    "geometricError" : 1.0
  }
}
```
will now generate an issue like this
```
Validation result:
{
  "date": "2022-10-04T15:00:06.894Z",
  "numErrors": 1,
  "numWarnings": 0,
  "issues": [
    {
      "type": "PROPERTY_MISSING",
      "path": "/geometricError",
      "message": "The 'geometricError' property is required",
      "severity": "ERROR"
    }
  ]
}
```

The same should be the case for _all_ required filelds.
