### ISSUE TITLE
3D Tiles Tools gzip

### ISSUE THREAD

**Issue by Ma-Wen** [CesiumGS/3d-tiles-validator#175]
After using ‘3D Tiles Tools gzip’ to compress 3d tiles files, the result is a binary file, how should I add it to cesium？

**Comment by chaitanyajalluri** [comment]
copy the files on local server "AnalyticalGraphicsInc/3d-tiles-samples" and access from there.

**Comment by javagl** [comment]
I assume that this is resolved (due to inactivity). Feel free to reopen if necessary.
