### ISSUE TITLE
How to carry update operation in 3D tiles.

### ISSUE THREAD

**Issue by 82siha1mpg** [CesiumGS/3d-tiles-validator#178]
Hi All, 
I wish to ask that, Is there any mechanism available to carry out update operations in 3D tiles? To elaborate: if there is an addition or deletion (building/object etc.) in 3D Model, how can I update all the nodes in 3D Tiles (b3dm etc.) without creating new tileset and removing the old one. ? 
Any help/suggestion is highly appreciated!! 
Thanks :)

**Comment by javagl** [comment]
It is not entirely clear what this question refers to. It is unlikely that it refers to one of the projects that are or have been maintained in this repository. It might be better to ask this in the repository of the tool that was used for creating the tilesets in the first place.
