### ISSUE TITLE
Drone Images to b3dm

### ISSUE THREAD

**Issue by aneeqabbasi** [CesiumGS/3d-tiles-validator#179]
I have drone images need to convert it into b3dm. How to convert it into b3dm or json? I have tried many things but it didn't work..
Thank You

**Comment by javagl** [comment]
A B3DM file usually contains _geometry_ data. Of course, this geometry data can also be textured. But when you mention "drone images", it may be necessary to provide further information about what the _actual_ input is. Information about the input formats (for imagery or photogrammetry) that can be uploaded to Cesium ion (and therefore, converted to 3D Tiles assets), refer to https://cesium.com/learn/3d-tiling/
