### ISSUE TITLE
Report when region boundingVolumes are < -Pi or > Pi

### ISSUE THREAD

**Issue by jerstlouis** [CesiumGS/3d-tiles-validator#204]
I would naturally expect latitude & longitude to be specified in degrees as it is the most commonly used human-friendly unit.
The behavior of wrong bounding volumes is very puzzling (e.g. things disappear when zooming in, no console output in CesiumJS), so it makes it very difficult to debug what could be a common mistake.

It would go a long way to warn about region bounding volumes mistakenly specified as degrees by checking against the -Pi/2..Pi and -Pi..Pi ranges.

**Comment by javagl** [comment]
This should have been closed (see https://github.com/CesiumGS/3d-tiles-validator/pull/222#issuecomment-1265905466 ).

Having an invalid bounding region like this
```
{
  "asset": {
    "version": "1.1"
  },
  "geometricError": 4.0,
  "root": {
    "boundingVolume": {
      "region": [
        181,
        91,
        -181,
        -91,
        10000,
        9999
      ]
    },
    "geometricError": 2.0
  }
}
```
will now generate issues like these
```
Validation result:
{
  "date": "2022-10-04T14:58:28.480Z",
  "numErrors": 6,
  "numWarnings": 0,
  "issues": [
    {
      "type": "BOUNDING_VOLUME_INCONSISTENT",
      "path": "/root/boundingVolume/region/0",
      "message": "The 'west' entry of the bounding region must be in [-180,180], but is 181",
      "severity": "ERROR"
    },
    {
      "type": "BOUNDING_VOLUME_INCONSISTENT",
      "path": "/root/boundingVolume/region/1",
      "message": "The 'south' entry of the bounding region must be in [-90,90], but is 91",
      "severity": "ERROR"
    },
    {
      "type": "BOUNDING_VOLUME_INCONSISTENT",
      "path": "/root/boundingVolume/region/2",
      "message": "The 'east' entry of the bounding region must be in [-180,180], but is -181",
      "severity": "ERROR"
    },
    {
      "type": "BOUNDING_VOLUME_INCONSISTENT",
      "path": "/root/boundingVolume/region/3",
      "message": "The 'north' entry of the bounding region must be in [-90,90], but is -91",
      "severity": "ERROR"
    },
    {
      "type": "BOUNDING_VOLUME_INCONSISTENT",
      "path": "/root/boundingVolume/region",
      "message": "The 'south' entry of the bounding region may not be larger than the 'north' entry, but the south is 91 and the north is -91",
      "severity": "ERROR"
    },
    {
      "type": "BOUNDING_VOLUME_INCONSISTENT",
      "path": "/root/boundingVolume/region",
      "message": "The minimum height of the bounding region may not be larger than the maximum height, but the minimum height is 10000 and the maximum height is 9999",
      "severity": "ERROR"
    }
  ]
}
```

**Comment by jerstlouis** [comment]
@javagl The test example does not seem right (and this would highlight the whole point of this issue).

The first 4 values of `"region"` need [are expected to be in **radians**](http://docs.opengeospatial.org/cs/18-053r2/18-053r2.html#32), not degrees.

> **6.7.3.1    Region**
The boundingVolume.region property is an array of six numbers that define the bounding geographic region with latitude, longitude, and height coordinates with the order [west, south, east, north, minimum height, maximum height]. Latitudes and longitudes are in the WGS 84 datum as defined in EPSG 4979 and are **in radians**. 

So the test should generate an error with e.g.,
```json
"region": [
        -4,
        2,
        -3.5,
        3,
        0,
        1000
      ]
```

The message also further adds to the confusion by contradicting the standard saying degrees are expected.
Unless this is changing in 3D Tiles Next and degrees are now expected?

**Comment by javagl** [comment]
Let's hope that there are not tooo many blunders in the validation that are as embarassing as this one. I took the values from https://epsg.io/4979 , but you're right: The values are supposed to be in radians.

**Comment by jerstlouis** [comment]
@javagl This really proves the importance of this issue :)
I made this same mistake myself multiple times, and I am quite sure it bites a large number of developers interacting directly with _3D Tiles_ tilesets.

Thanks for the fix ( I am guessing the Cesium loader itself uses the validator, so that this would also show up if loading a wrongly constructed tileset? )

**Comment by javagl** [comment]
CesiumJS will not use the validator. 

This has several reasons, with differences in the ... "technical profoundness" that I can articulate here. Some seemingly minor ones are: The validator uses (parts of) CesiumJS, e.g. the `Matrix4` class - so the direction of dependency would not be clear. The validator is written in TypeScript, which may only be a slight inconvenience in some ways.

A more profound reason is that the validation is a dedicated task, and the high-level idea is: When a tileset is "valid", then it can be displayed in CesiumJS (and in any other viewer that follows the specification) without problems. 

The viewer itself should not have to perform a bazillion low-level 'validation checks' that (in most cases) are unnecessary. When it parses a JSON, then it should be able to assume that `tileset.geometricError` is a number, and not a string. (Much of that is still checked in CesiumJS, but disabled via debug pragmas by default). On top of that, the validator can do things that can not be done reasonably in CesiumJS. For example, CesiumJS may load a `tileset.json`. It will load some tile content, with a low level of detail. Somewhere deeeeply hidden in the tile hiearchy might be a `tile` with a `content` that refers to a B3DM that contains a GLB that has an error. At which point in time should that be "validated"? (CesiumJS should certainly not casually run the glTF-Validator for each tile content ;-)). 

Or to put it that way: The validator is rather targeting tools/applications that _create_ tilesets. They can validate their output, and see whether it follows the spec. If it does, it can be rendered (efficiently, without wasting time for further validation checks at runtime).

**Comment by jerstlouis** [comment]
Thank you very much for the detailed explanation @javagl.
It has been 2 years since I filed this issue, and I don't recall whether it was the validator or Cesium JS that I was using at the time.
I do understand the performance reason for not running the validator for every tile.
