### ISSUE TITLE
running combine

### ISSUE THREAD

**Issue by lihengxin** [CesiumGS/3d-tiles-validator#214]
“The ‘path’ argument must be of type string. Received undefined”
i dont konw why does this problem occur。
![image](https://user-images.githubusercontent.com/22095590/133407029-fd0ed647-097c-4b6a-8cf1-e071337b2676.png)

**Comment by lihengxin** [comment]
![image](https://user-images.githubusercontent.com/22095590/133414237-79cceb3c-3b8e-4480-9fc7-292829c2de7b.png)
I have the same problem using the self-contained example

**Comment by getinthedamnbox** [comment]
Fixed by #217.
