### ISSUE TITLE
Upgrading to glTF 2.0.

### ISSUE THREAD

**Issue by dovydaspocius** [CesiumGS/3d-tiles-validator#220]
after running upgrading command got upgrade to 1.0 version . Expected 2.0 version
![image](https://user-images.githubusercontent.com/75212069/175251041-3b19db15-39e1-48fb-93d7-2963d04b259d.png)

**Comment by ptrgags** [comment]
Hi @dovydaspocius,

To explain what this script is doing, it's upgrading the tileset to 3D Tiles 1.0. Meanwhile, any glTF models embedded in the `.b3dm` or `.i3dm` content files are upgraded to glTF 2.0.

See the documentation comment here: https://github.com/CesiumGS/3d-tiles-validator/blob/main/tools/lib/upgradeTileset.js#L26

**Comment by dovydaspocius** [comment]
but after loading in cesium, still same error
![image](https://user-images.githubusercontent.com/75212069/175331063-ac6baecd-bea7-42e3-95fe-5e54601e9bbe.png)

**Comment by lilleyse** [comment]
@ptrgags does that error also get printed if the glTF 2.0 uses `KHR_techniques_webgl`?

@baothientran you were working on a branch that converted glTF 1.0 to glTF 2.0 without using `KHR_techniques_webgl`, right? Could you point @dovydaspocius to that?

@dovydaspocius if you're able to share the 3D Tiles or even a single .b3dm that would be helpful

**Comment by dovydaspocius** [comment]
as the full 3d tiles have too large a capacity, i'll put here single b3dm file
[L15_0000.zip](https://github.com/CesiumGS/3d-tiles-validator/files/8968620/L15_0000.zip)

**Comment by baothientran** [comment]
@dovydaspocius  there is https://github.com/CesiumGS/3d-tiles-validator/tree/2.0-tools-unlit that fixes the invalid glTF above. The small problem is I hardcode the diffuse texture from KHR_techiniques_webgl and use it for the base color texture in glTF 2.0, so it may not work with your b3dm. But if it's the case, it will fallback to white color for now. I will look into your b3dm to fix that

**Comment by baothientran** [comment]
@dovydaspocius the attached b3dm doesn't seem to have geometry in it. Can you attach another b3dm with mesh and material?

**Comment by baothientran** [comment]
@dovydaspocius it's in a different branch `2.0-tools-unlit` that isn't merged to main

**Comment by dovydaspocius** [comment]
@baothientran still same result :((

**Comment by baothientran** [comment]
yeah the branch is a little old, so some messages like that are expected. Do you have any b3dm files with geometry and material I can borrow? Also, what are the error messages that you see currently?

**Comment by dovydaspocius** [comment]
after upgrade, got same meeseges :
![image](https://user-images.githubusercontent.com/75212069/175353451-4f0c8daf-f858-43af-a0ca-d5724232338f.png)
after that i puted it in cesium ion and saw same message:
![image](https://user-images.githubusercontent.com/75212069/175353790-df8c6b9e-1f12-44d6-94d1-0ca96f74a817.png)

here is my part of 3 tile:
[project.zip](https://github.com/CesiumGS/3d-tiles-validator/files/8969339/project.zip)
in 100 folder extract all these zip folders:
[first_part.zip](https://github.com/CesiumGS/3d-tiles-validator/files/8969343/first_part.zip)
[second part.zip](https://github.com/CesiumGS/3d-tiles-validator/files/8969345/second.part.zip)
[third_part.zip](https://github.com/CesiumGS/3d-tiles-validator/files/8969347/third_part.zip)
[all_b3dm_in_this_dir.zip](https://github.com/CesiumGS/3d-tiles-validator/files/8969349/all_b3dm_in_this_dir.zip)

sorry for this mess , just cant upload bigger than 25mb zip

adding how should look roots:
![image](https://user-images.githubusercontent.com/75212069/175357010-067d771a-5e4c-4bf6-922f-a74e80e9323d.png)
in 100 folder:
![image](https://user-images.githubusercontent.com/75212069/175357181-293409ee-5ea7-4e35-ae6e-996024a085eb.png)

**Comment by baothientran** [comment]
@dovydaspocius sorry for getting back late to you, I tried out the tool and it seems to work correctly for me:

![Capture](https://user-images.githubusercontent.com/20376598/175864262-7d55882b-9781-494b-a054-6db176b47773.PNG)

A couple thing to check is that the tool output the upgraded tileset in a different directory that has `upgraded` postfix in its name, so please make sure you use this directory instead of the old one. Something like this:

![Capture](https://user-images.githubusercontent.com/20376598/175864545-af49b313-9d2b-4935-8695-af5086a3071d.PNG)
 
Please let me know if the problem still happens

**Comment by dovydaspocius** [comment]
it worked! thank you! The problem was that git clone didn't work properly and download wrong older files from https://github.com/CesiumGS/3d-tiles-validator/tree/main/tools  , so i needed download zip and then worked fine!

**Comment by baothientran** [comment]
Since this is resolved, I will close it for now. Please feel free to re-open the issue if any problems arise

**Comment by dovydaspocius** [comment]
hello,
program is unable upgrade files:
![image](https://user-images.githubusercontent.com/75212069/177338151-7d942b9c-b4d7-43b2-8f7a-099d4f5dce6e.png)

"Data" folder have only b3dm files:
![image](https://user-images.githubusercontent.com/75212069/177338544-8f0960a0-3c2c-4c44-87bf-d6012a21838c.png)

**Comment by baothientran** [comment]
@dovydaspocius it seems to fail because the tileset.json points to some missing files, e.g  `vilnius_visas\vilnius_visas\Data\332\L16_33203.json`

Do you wanna skip those files during upgrading?

**Comment by dovydaspocius** [comment]
yes, i want to skip those files. So i need to change root json file?

**Comment by baothientran** [comment]
I just whip up something really quick to upgrade b3dms only if you want to give it a try https://github.com/CesiumGS/3d-tiles-validator/tree/2.0-tools-hack.

It doesn't work for tileset.json currently though

**Comment by dovydaspocius** [comment]
it worked!!! Thank you again!
