### ISSUE TITLE
npm install fails with Node 19

### ISSUE THREAD

**Issue by here-abarany** [CesiumGS/3d-tiles-validator#245]
The version of the better-sqlite3 defined in package.json fails to build with Node 19. [better-sqlite3 8.0.0](https://github.com/WiseLibs/better-sqlite3/releases/tag/v8.0.0) is required to build against Node 19.

**Comment by javagl** [comment]
This has been addressed in the 0.2.0 release (as part of https://github.com/CesiumGS/3d-tiles-validator/issues/224 , which contained a few other fixes, beyond what the title of that PR suggests).

The version of `better-sqlite3` is now set to `^8.0.1`, which is compatible with Node 19. (The minimum Node version that is supported is 14, and it has been tested on both versions).
