### ISSUE TITLE
ValidFeatureIdAttributeWithByteStride.glb not a 3D Tile

### ISSUE THREAD

**Issue by bertt** [CesiumGS/3d-tiles-validator#295]
Maybe it's intentional, but the file ValidFeatureIdAttributeWithByteStride.glb only has custom vertex attribute _FEATURE_ID_0, but no 3D Tiles extensions are used, so the name of the file is confusing (there is no FeatureID).  

https://github.com/CesiumGS/3d-tiles-validator/blob/main/specs/data/gltfExtensions/meshFeatures/ValidFeatureIdAttributeWithByteStride.glb

**Comment by javagl** [comment]
That was not intentional. A fix and description for why this happened is in https://github.com/CesiumGS/3d-tiles-validator/pull/296
