### ISSUE TITLE
Failing on glTF with meshopt fallback buffer

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles-validator#323]
I'm trying to validate a tileset with .gltf files that use `EXT_meshopt_compression` and it fails when it encounters a meshopt fallback buffer which doesn't have a URI.

![image](https://github.com/user-attachments/assets/35396169-0f4a-403d-9850-045758e396cb)

![image](https://github.com/user-attachments/assets/af1b3af4-e2a8-493d-8625-b6b742cb3493)

![image](https://github.com/user-attachments/assets/1e718f15-92bd-4a5d-b71b-f644eab52f16)

**Comment by javagl** [comment]
This actually stems from some of the underlying, fundamental classes in the `3d-tiles-tools` that did not properly handle that case of "fallback buffers" that may appear in `EXT_meshopt_compression`. (This is a bit obscure, and I'll have to read/check this more thoroughly).

A draft for fixing this is at https://github.com/CesiumGS/3d-tiles-tools/pull/160
