### ISSUE TITLE
Validator - validate glb

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles-validator#98]
@Rudraksha20

After the small tileset.json fixes are squared away we will work on validating the glTF models that are embedded within b3dm and i3dm tiles. This will be a multi-part issue that we'll add on to as we go.

Open a PR for each checkbox.

* [x] Check that the embedded glb is version 2.0. If not return an error message.
* [ ] Check that the glb meets the glTF 2.0 schema. We'll need to use the [glTF validator](https://github.com/KhronosGroup/glTF-Validator) here, probably the `dev` branch. Most likely the glTF validator will need to be called via a child process.

**Comment by javagl** [comment]
As mentioned in https://github.com/CesiumGS/3d-tiles-validator/pull/222#issuecomment-1265905466 : The updated validator will validate glTF assets that are found as tile content, using the glTF validator.

The issues that are found by the glTF validator will be the `causes` of a single `CONTENT_VALIDATION_ERROR` that is created in these cases, like in this example:
```
Validation result:
{
  "date": "2022-10-04T15:03:45.676Z",
  "numErrors": 1,
  "numWarnings": 0,
  "issues": [
    {
      "type": "CONTENT_VALIDATION_ERROR",
      "path": "tiles/glTF/TriangleGlbWithErrors/TriangleGlbWithInvalidLength.glb",
      "message": "Content tiles/glTF/TriangleGlbWithErrors/TriangleGlbWithInvalidLength.glb caused validation errors",
      "severity": "ERROR",
      "causes": [
        {
          "type": "CONTENT_VALIDATION_ERROR",
          "message": "Chunk (0x004e4942) length (44) does not fit total GLB length.",
          "severity": "ERROR"
        },
        {
          "type": "CONTENT_VALIDATION_ERROR",
          "message": "Declared length (680) does not match GLB length (684).",
          "severity": "ERROR"
        }
      ]
    }
  ]
}
```
